name: Build Succeed on PR

on:
  pull_request:
    branches:
      - my-branch
jobs: 
  build:
    name: build the project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      
      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build